In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
import nfp

print(f"tensorflow {tf.__version__}")
print(f"nfp {nfp.__version__}")

tensorflow 2.8.0
nfp 0.3.8+0.ge19d476.dirty


In [2]:
# Load the input data, here YSI (10.1016/j.combustflame.2017.12.005)
# ysi.csv available from https://github.com/pstjohn/YSIs_for_prediction/
ysi = pd.read_csv('../data/ysi.csv')
ysi.head()

Species       CAS  Ref      Type     YSI  YSI_err  \
0          1,2-diphenylbenzene   84-15-1  2.0  aromatic  1338.9     50.0   
1  cyclopenta[def]phenanthrene  203-64-5  2.0  aromatic  1312.8     73.5   
2                 fluoranthene  206-44-0  2.0  aromatic  1291.9     72.4   
3          1,3-diphenylbenzene   92-06-8  2.0  aromatic  1286.6     72.3   
4                       pyrene  129-00-0  2.0  aromatic  1250.1     70.1   

                           SMILES  
0    c1ccc(-c2ccccc2-c2ccccc2)cc1  
1     c1cc2c3c(c1)ccc1cccc(c13)C2  
2    c1ccc2c(c1)-c1cccc3cccc-2c13  
3  c1ccc(-c2cccc(-c3ccccc3)c2)cc1  
4      c1cc2ccc3cccc4ccc(c1)c2c34

In [3]:
# Split the data into training, validation, and test sets
valid, test, train = np.split(ysi.SMILES.sample(frac=1., random_state=1), [50, 100])
len(train), len(valid), len(test)

(341, 50, 50)

In [4]:
# Define how to featurize the input molecules
from nfp.preprocessing.mol_preprocessor import SmilesPreprocessor
from nfp.preprocessing.features import get_ring_size


def atom_featurizer(atom):
    """ Return an string representing the atom type
    """

    return str((
        atom.GetSymbol(),
        atom.GetIsAromatic(),
        get_ring_size(atom, max_size=6),
        atom.GetDegree(),
        atom.GetTotalNumHs(includeNeighbors=True)
    ))


def bond_featurizer(bond, flipped=False):
    """ Get a similar classification of the bond type.
    Flipped indicates which 'direction' the bond edge is pointing. """
    
    if not flipped:
        atoms = "{}-{}".format(
            *tuple((bond.GetBeginAtom().GetSymbol(),
                    bond.GetEndAtom().GetSymbol())))
    else:
        atoms = "{}-{}".format(
            *tuple((bond.GetEndAtom().GetSymbol(),
                    bond.GetBeginAtom().GetSymbol())))
    
    btype = str(bond.GetBondType())
    ring = 'R{}'.format(get_ring_size(bond, max_size=6)) if bond.IsInRing() else ''
    
    return " ".join([atoms, btype, ring]).strip()


preprocessor = SmilesPreprocessor(atom_features=atom_featurizer, bond_features=bond_featurizer,
                                  explicit_hs=False)

In [5]:
# Initially, the preprocessor has no data on atom types, so we have to loop over the 
# training set once to pre-allocate these mappings
print("before pre-allocating")
print(preprocessor.atom_tokenizer._data)

for smiles in train:
    preprocessor(smiles, train=True)
    
print()
print("after pre-allocating")
print(preprocessor.atom_tokenizer._data)

before pre-allocating
{'unk': 1}

after pre-allocating
{'unk': 1, "('C', False, 0, 1, 3)": 2, "('C', False, 0, 2, 2)": 3, "('C', False, 0, 3, 0)": 4, "('O', False, 0, 1, 0)": 5, "('O', False, 0, 2, 0)": 6, "('C', False, 0, 1, 2)": 7, "('C', False, 0, 2, 1)": 8, "('C', False, 0, 3, 1)": 9, "('C', False, 0, 4, 0)": 10, "('C', True, 'max', 2, 1)": 11, "('C', True, 'max', 3, 0)": 12, "('C', False, 'max', 2, 2)": 13, "('O', False, 0, 1, 1)": 14, "('C', False, 0, 1, 1)": 15, "('C', False, 0, 2, 0)": 16, "('C', False, 'max', 3, 1)": 17, "('N', False, 0, 1, 0)": 18, "('Br', False, 0, 1, 0)": 19, "('C', False, 'max', 2, 1)": 20, "('C', True, 5, 3, 0)": 21, "('C', False, 5, 2, 2)": 22, "('C', False, 5, 2, 1)": 23, "('C', False, 5, 3, 1)": 24, "('C', False, 5, 3, 0)": 25, "('C', False, 'max', 3, 0)": 26, "('O', False, 5, 2, 0)": 27, "('O', False, 'max', 2, 0)": 28, "('F', False, 0, 1, 0)": 29, "('C', True, 5, 2, 1)": 30, "('C', False, 'max', 4, 0)": 31, "('Cl', False, 0, 1, 0)": 32, "('C', False,

2022-02-28 15:43:02.624213: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
# Main input types for a SMILES-based prediction
smiles = 'CCO'

# Atom types, as integer classes
preprocessor(smiles, train=True)['atom']

array([ 2,  3, 14], dtype=int32)

In [7]:
# Bond types, as integer classes
preprocessor(smiles, train=True)['bond']

array([2, 2, 5, 6], dtype=int32)

In [8]:
# A connectivity array, where row i indicates bond i connects atom j to atom k
preprocessor(smiles, train=True)['connectivity']

array([[0, 1],
       [1, 0],
       [1, 2],
       [2, 1]])

In [9]:
# Construct the tf.data pipeline. There's a lot of specifying data types and
# expected shapes for tensorflow to pre-allocate the necessary arrays. But 
# essentially, this is responsible for calling the input constructor, batching 
# together multiple molecules, and padding the resulting molecules so that all
# molecules in the same batch have the same number of atoms (we pad with zeros,
# hence why the atom and bond types above start with 1 as the unknown class)

train_dataset = tf.data.Dataset.from_generator(
    lambda: ((preprocessor(row.SMILES, train=False), row.YSI)
             for i, row in ysi[ysi.SMILES.isin(train)].iterrows()),
    output_signature=(preprocessor.output_signature, tf.TensorSpec((), dtype=tf.float32)))\
    .cache().shuffle(buffer_size=200)\
    .padded_batch(batch_size=64)\
    .prefetch(tf.data.experimental.AUTOTUNE)


valid_dataset = tf.data.Dataset.from_generator(
    lambda: ((preprocessor(row.SMILES, train=False), row.YSI)
             for i, row in ysi[ysi.SMILES.isin(valid)].iterrows()),
    output_signature=(preprocessor.output_signature, tf.TensorSpec((), dtype=tf.float32)))\
    .cache()\
    .padded_batch(batch_size=64)\
    .prefetch(tf.data.experimental.AUTOTUNE)

In [10]:
inputs, outputs = next(train_dataset.as_numpy_iterator())
inputs['atom']

2022-02-28 15:43:03.219907: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


array([[ 2,  4,  5, ...,  0,  0,  0],
       [ 2,  3,  3, ...,  0,  0,  0],
       [ 2,  3,  8, ...,  0,  0,  0],
       ...,
       [ 2,  4,  2, ...,  0,  0,  0],
       [11, 11, 21, ...,  0,  0,  0],
       [ 7,  4,  2, ...,  0,  0,  0]], dtype=int32)

In [11]:
## Define the keras model
from tensorflow.keras import layers

# Input layers
atom = layers.Input(shape=[None], dtype=tf.int64, name='atom')
bond = layers.Input(shape=[None], dtype=tf.int64, name='bond')
connectivity = layers.Input(shape=[None, 2], dtype=tf.int64, name='connectivity')

num_features = 8  # Controls the size of the model

# Convert from a single integer defining the atom state to a vector
# of weights associated with that class
atom_state = layers.Embedding(preprocessor.atom_classes, num_features,
                              name='atom_embedding', mask_zero=True)(atom)

# Ditto with the bond state
bond_state = layers.Embedding(preprocessor.bond_classes, num_features,
                              name='bond_embedding', mask_zero=True)(bond)

# Here we use our first nfp layer. This is an attention layer that looks at
# the atom and bond states and reduces them to a single, graph-level vector. 
# mum_heads * units has to be the same dimension as the atom / bond dimension
global_state = nfp.GlobalUpdate(units=8, num_heads=1)([atom_state, bond_state, connectivity])

for _ in range(3):  # Do the message passing
    new_bond_state = nfp.EdgeUpdate()([atom_state, bond_state, connectivity, global_state])
    bond_state = layers.Add()([bond_state, new_bond_state])
    
    new_atom_state = nfp.NodeUpdate()([atom_state, bond_state, connectivity, global_state])
    atom_state = layers.Add()([atom_state, new_atom_state])
    
    new_global_state = nfp.GlobalUpdate(units=8, num_heads=1)(
        [atom_state, bond_state, connectivity, global_state]) 
    global_state = layers.Add()([global_state, new_global_state])

    
# Since the final prediction is a single, molecule-level property (YSI), we 
# reduce the last global state to a single prediction.
ysi_prediction = layers.Dense(1)(global_state)

# Construct the tf.keras model
model = tf.keras.Model([atom, bond, connectivity], [ysi_prediction])

In [12]:
model.compile(loss='mae', optimizer=tf.keras.optimizers.Adam(1E-3))

# Fit the model. The first epoch is slower, since it needs to cache
# the preprocessed molecule inputs
model.fit(train_dataset, validation_data=valid_dataset, epochs=25)

Epoch 1/25
6/6 [==============================] - 7s 343ms/step - loss: 192.5133 - val_loss: 156.2761
Epoch 2/25
6/6 [==============================] - 0s 13ms/step - loss: 191.7135 - val_loss: 155.0828
Epoch 3/25
6/6 [==============================] - 0s 18ms/step - loss: 190.0994 - val_loss: 152.4968
Epoch 4/25
6/6 [==============================] - 0s 16ms/step - loss: 186.4315 - val_loss: 146.0459
Epoch 5/25
6/6 [==============================] - 0s 14ms/step - loss: 176.6360 - val_loss: 127.8532
Epoch 6/25
6/6 [==============================] - 0s 15ms/step - loss: 162.1535 - val_loss: 122.6636
Epoch 7/25
6/6 [==============================] - 0s 15ms/step - loss: 155.8913 - val_loss: 116.2806
Epoch 8/25
6/6 [==============================] - 0s 15ms/step - loss: 149.0768 - val_loss: 112.1541
Epoch 9/25
6/6 [==============================] - 0s 15ms/step - loss: 143.1971 - val_loss: 109.4144
Epoch 10/25
6/6 [==============================] - 0s 15ms/step - loss: 127.7537 - val_los

In [13]:
# Here, we create a test dataset that doesn't assume we know the values for the YSI

test_dataset = tf.data.Dataset.from_generator(
    lambda: (preprocessor(smiles, train=False)
             for smiles in test),
    output_signature=preprocessor.output_signature)\
    .padded_batch(batch_size=64)\
    .prefetch(tf.data.experimental.AUTOTUNE)

In [14]:
# Here are the predictions on the test set
test_predictions = model.predict(test_dataset)
test_db_values = ysi.set_index('SMILES').reindex(test).YSI.values

np.abs(test_db_values - test_predictions.flatten()).mean()

40.749891374588